### ISSUE TITLE
Slackware support?

### ISSUE THREAD

**Issue by xexpanderx** [ThatOneCalculator/NerdFetch#15]
Any chance you will add support for Slackware? :)

Thx!

**Comment by ThatOneCalculator** [comment]
Never used Slackware before. What's the package manager?

**Comment by xexpanderx** [comment]
slackpkg is the official one (there is also pkgtools but that is more basic).

**Comment by ThatOneCalculator** [comment]
Can you send the command to list your packages? Piping it into `wc -l` should result in the correct number of packages.

**Comment by ThatOneCalculator** [comment]
Nvm I can `ls /var/log/packages/ | wc -l` and just check if `slackpkg` exists. I'll add a commit when I'm on my computer (I'm on mobile rn)

**Comment by xexpanderx** [comment]
Hey, yes, doing ls on /var/log/packages/ should be enough.

**Comment by ThatOneCalculator** [comment]
@xexpanderx ok can you clone and test it? Let me know if it all goes good :)

**Comment by xexpanderx** [comment]
![Screenshot_2021-01-02_21-33-24](https://user-images.githubusercontent.com/10048240/103465229-58ec6600-4d42-11eb-85b7-1a9177261ff6.png)

Thx, (rpm) still shows up though.

**Comment by xexpanderx** [comment]
slackpkg is located at /usr/sbin/slackpkg btw.

**Comment by ThatOneCalculator** [comment]
Ah, didn't realize that it could've shown rpm. One sec.

**Comment by ThatOneCalculator** [comment]
Hm, `slackpkg` is close to the end on line 38, after `rpm`. Are you sure you have the latest version? And can you send the output of `which slackpkg`?

**Comment by xexpanderx** [comment]
Yes, the thing is, slackpkg is located at /usr/sbin, not /usr/bin. So, as a regular user, I dont have /usr/sbin/ in my path. So, a which will not find slackpkg. Maybe I can just add /usr/sbin/ to my PATH.

**Comment by xexpanderx** [comment]
I added /usr/sbin/slackpkg on that line instead of slackpkg. Thanks for your help!

**Comment by ThatOneCalculator** [comment]
Ok! So it should be 
```
manager=$(which nix-env yum zypper dnf rpm apt brew port pacman xbps-query pkg emerge cave apk kiss pmm /usr/sbin/slackpkg yay cpm eopkg 2>/dev/null)
```
?

**Comment by ThatOneCalculator** [comment]
@xexpanderx you there?

**Comment by xexpanderx** [comment]
Hi, yes, sorry, exactly like that.

**Comment by ThatOneCalculator** [comment]
Cool. I'll close this for now, assuming that everything works.
