### ISSUE TITLE
Doesn't run on macOS

### ISSUE THREAD

**Issue by gracjankn** [ThatOneCalculator/NerdFetch#17]
I tested the script on macOS 11.1.

The command `sudo install -m755 nerdfetch /usr/bin/nerdfetch` from manual installation instruction shows error `install: /usr/bin/nerdfetch: Operation not permitted`.

If instead I manually place it anywhere in the $PATH and try to run it I only see the error `./nerdfetch: line 8: /etc/os-release: No such file or directory`.

When line 8 is commented, I see error `cat: /proc/sys/kernel/hostname: No such file or directory` followed by the desired output.

When lines 8 and 9 are commented, everything works correctly.

**Comment by ThatOneCalculator** [comment]
> The command sudo install -m755 nerdfetch /usr/bin/nerdfetch from manual installation instruction shows error install: /usr/bin/nerdfetch: Operation not permitted.

You don't have administrator permissions on your system. 

> When line 8 is commented, I see error cat: /proc/sys/kernel/hostname: No such file or directory followed by the desired output.
> When lines 8 and 9 are commented, everything works correctly.

That should be fixed.
