### ISSUE TITLE
Distro Logo

### ISSUE THREAD

**Issue by Tomoghno** [ThatOneCalculator/NerdFetch#24]
Please Can You add Fedora and other distro logos

**Comment by ThatOneCalculator** [comment]
No. NerdFetch is meant to be as minimal as possible, and Fedora is a cringe distro anyways.

**Comment by Tomoghno** [comment]
> No. NerdFetch is meant to be as minimal as possible, and Fedora is a cringe distro anyways.

Fedora is used by Many Professionals who work in IT and don't get me started on how great DNF package manager is.
