### ISSUE TITLE
Symbols not displaying correctly using Fira Code

### ISSUE THREAD

**Issue by IlmastroStefanuzzo** [ThatOneCalculator/NerdFetch#26]
**Symbols not displaying correctly using Fira Code**

**To Reproduce**
1. Run nerdfetch with Fira Code fonts

**Expected behavior**
Some symbols representing the informations type should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/71498817/127169367-2aeb4fc1-5748-4008-862a-fc85cc0cb0ee.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Install method: `yay -S nerdfetch`

**Comment by ThatOneCalculator** [comment]
You need FiraCode Nerd Font, not just the regular version. https://nerdfonts.com

**Comment by IlmastroStefanuzzo** [comment]
Oh, thanks
