### ISSUE TITLE
What's the font in the screenshot?

### ISSUE THREAD

**Issue by WhyNotHugo** [ThatOneCalculator/NerdFetch#32]
Hope you don't mind the mildly-offtopic question, but: what's the font used in the screenshot of a terminal in the README?

Cheers!

**Comment by ThatOneCalculator** [comment]
Cartograph CF :)
It's a paid font, but if you look in my [dots](https://github.com/thatonecalculator/bspwm-dotfiles), you can download it for free

**Comment by WhyNotHugo** [comment]
Thanks!
