### ISSUE TITLE
Fallback for os-release?

### ISSUE THREAD

**Issue by polluks** [ThatOneCalculator/NerdFetch#49]
Our provider removed this file.
nerdfetch: line 23: /etc/os-release: No such file or directory
```
      ___     ********@web32.alfahosting-server.de
     (.. \    
     (<> |      4.18.0
    //  \ \   󰍛  25153/39949 MiB (62%)
   ( |  | /|  󰏔  516 (bin)
  _/\ __)/_)  󰅶  175 days, 16 hours, 39 mins
  \/-____\/     ██████████████████
```
By the way
```
$ cat /proc/version
Linux version 4.18.0-477.13.1.lve.el7h.x86_64 (mockbuild@rbuildfarm03.corp.cloudlinux.com) (gcc version 8.2.1 20180905 (Red Hat 8.2.1-3) (GCC)) #1 SMP Thu Jun 1 16:49:27 UTC 2023

**Comment by ThatOneCalculator** [comment]
`/proc/version` doesn't give the distro name. You should maybe be using a different provider if they're removing critical files and giving you an outdated/insecure kernel version...

**Comment by ThatOneCalculator** [comment]
What's the output of
- `ls /etc/*-release`
- `lsb_release -a`

**Comment by polluks** [comment]
> `/proc/version` doesn't give the distro name. You should maybe be using a different provider if they're removing critical files and giving you an outdated/insecure kernel version...

"Red Hat" is a the distro name IMHO. In the past we had Debian.

**Comment by ThatOneCalculator** [comment]
I'm not going to parse through all that, it's incredibly unreliable. Can you please just give the outputs if the two commands I posted?

**Comment by polluks** [comment]
Indeed, however there was no output at all.

Am Fr., 19. Jan. 2024 um 17:30 Uhr schrieb Kainoa Kanter <
***@***.***>:

**Comment by ThatOneCalculator** [comment]
There's no output for the `ls` and for the `lsb_release -a`?

**Comment by polluks** [comment]
No other files or commands. 
Just /proc gave me the hint about Red Hat.

**Comment by ThatOneCalculator** [comment]
Not having `lsb_release` is VERY concerning. LSB means "Linux Standard Base". I'm sorry, but you're simply using too esoteric of a system to reasonably support.
