### ISSUE TITLE
Debian packages?

### ISSUE THREAD

**Issue by polluks** [ThatOneCalculator/NerdFetch#52]
![grafik](https://github.com/ThatOneCalculator/NerdFetch/assets/4707573/fc87a7f8-2fe2-4082-9804-c55e82e7fa0f)
even better is your `dpkg-query -W | wc -l` but it's not executed

**Comment by ThatOneCalculator** [comment]
It's because you have pacstall which is considered to be the preferred manager. You can modify the script for your needs.
